import {
  LM_XML_POLY, LM_XML_COTTON, LM_XML_COTTON_DEFAULT,
  LM_ROLL_POLY, LM_ROLL_COTTON, LM_ROLL_COTTON_DEFAULT,
} from "../../shared/printWidths.js";

const flag = (name, keyword) => (name.toLowerCase().includes(keyword) ? 1 : 0);

const COTTON_NAMES = [
  "Cotton Slub",
  "Stretch Lycra French Terry",
  "Poppy Lycra Jersey",
  "Organic Jersey Interlock",
  "Organic Iris Jersey",
  "Single Cotton Elastane Jersey",
  "DSTK - Stretch Lycra French Terry",
  "Organic Drill Natural",
  "Panama",
  "Organic Leve Panama Natural",
  "Hector Linen",
  "Poplin",
  "Light Twill",
  "Organic Drill Optic",
  "Organic Optic Calico",
  "Satin",
  "Top Sateen",
  "Organic Blossom Muslin Gauze",
  "Organic Panama Natural",
  "Organic Leve Cotton Panama Natural",
  "Organic Jasmine Lycra Jersey",
  "Cotton Denim",
  "Organic Poplin",
  "Organic Satin",
  "Optic White Organic Panama",
  "Melino Linen",
  "Limani Linen",
  "DSTK - Organic Jersey Interlock",
  "Organic Stratos Linen",
  "Organic Nimbus Linen",
  "Organic Calico Natural",
  "Calico Plain Cotton",
  "Drill",
];

const POLY_NAMES = [
  "Eco Pique",
  "Micro Linen",
  "Slub Chiffon",
  "Chiffon",
  "DSTK - Recycled Ripstop",
  "Gloss Satin",
  "Tentex (Water Repellant)",
  "Eco Jersey",
  "Eco Display FR",
  "Easy Care Twill",
  "DSTK - Shimmer Velvet",
  "Eco Telis Velvet - Domestic FR",
  "Eco Basketweave",
  "DSTK - Velvet Satin",
  "DSTK - Heavy Bandage Crepe",
  "DSTK - Shark Satin",
  "DSTK - Eco Pique",
  "Eco rPet Canvas",
  "Eco Micro Jersey",
  "Eco Telis Velvet - Non FR",
  "Crepe de Chine",
  "Panama FR",
  "Heavy Lycra 210",
  "Massey Crepe",
  "Eco Jogger Fleece Back",
  "Plainweave FR",
  "Palatine Velvet FR",
  "Lining",
  "Eco Surf Pro",
  "Ligos Velvet",
  "DSTK - Eco Jersey",
  "Fine Stripe Chiffon",
  "Eco Recycled Ripstop",
  "Voile FR",
  "Waterproof Suede FR",
  "DSTK - Fluid Twill",
  "DSTK - SoftShell Ultra",
  "Summer Voile",
  "Dupioni FR",
  "Crinkle Gauze",
  "Eco Fleece",
  "Eco Soft Tulle",
  "DSTK - Eco Bridal Twill",
  "Metallic Silver Satin Twill",
  "DSTK - Poly Tulle",
  "DSTK - Paros Stretch Twill",
  "Eco Upholstery FR",
  "Eco Gloss Satin",
  "Avio Cotton Mix",
  "Neraki Waterproof Canvas FR (Water Repellant)",
  "Cora Canvas",
  "Eco Sprint Knit",
  "DSTK - Micro Linen",
  "Recycled Eco Lycra",
  "DSTK - Flat Velvet",
  "Eco Power Net",
  "Heavy Satin FR",
  "Scuba Bodyfit",
  "Oslo FR",
  "Aqua Plain Tex - PUL (Water Repellant)",
  "Diago Stretch",
  "Velvet",
  "Duchess Satin",
  "Luxe Velvet",
  "3-Pass Blackout FR",
  "Bayeux Upholstery",
  "Leos Cotton Mix",
  "Eco Velvet",
  "DSTK - Heavy Chenille",
  "Eco Dynamica Lycra",
  "Eco Mali Crepe",
  "Organza",
  "Plutus Velvet FR",
  "Active Eco Lycra",
  "DSTK - Slub Chiffon",
  "Easy Care Panama",
  "Eco Glitter Dot Lycra",
  "Eco Linen Look",
  "Eco Lotus Twill (Water Repellant)",
  "Eco Satin Flow",
  "Eco Silk Twill",
  "Eco Super Fine Chiffon",
  "Georgette",
  "Faux Silky Satin",
  "Eco Faux Silky Satin",
  "Eco Taffeta",
  "Eco Chiffon",
  "Stretch Jersey",
];

export const DEFAULT_FABRICS = [
  ...COTTON_NAMES.map((name) => ({
    name,
    type: "Cottons",
    xmlWidth: LM_XML_COTTON[name] ?? LM_XML_COTTON_DEFAULT,
    rollWidth: LM_ROLL_COTTON[name] ?? LM_ROLL_COTTON_DEFAULT,
    isVelvet: 0,
    isLinen: flag(name, "linen"),
    isBlossom: flag(name, "blossom"),
  })),
  ...POLY_NAMES.map((name) => ({
    name,
    type: "Polyesters",
    xmlWidth: LM_XML_POLY,
    rollWidth: LM_ROLL_POLY,
    isVelvet: flag(name, "velvet"),
    isLinen: flag(name, "linen"),
    isBlossom: 0,
  })),
];

export const DEFAULT_FABRIC_GLOBALS = {
  marginCotton: 10,
  marginPoly: 5,
  defaultXmlWidthCotton: LM_XML_COTTON_DEFAULT,
  defaultXmlWidthPoly: LM_XML_POLY,
  defaultRollWidthCotton: LM_ROLL_COTTON_DEFAULT,
  defaultRollWidthPoly: LM_ROLL_POLY,
};
