import {
  LuFileX,
  LuPrinter,
  LuRuler,
  LuLayers,
  LuZap,
  LuThermometer,
  LuWaves,
  LuGhost,
  LuSparkles,
  LuPalette,
  LuEllipsis,
  LuBot,
  LuRefreshCw,
  LuImageOff,
} from "react-icons/lu";

export const ROLLBACK_REASONS = [
  { code: "MISSING_JOB",      label: "Missing job",      icon: LuFileX,       iconName: "LuFileX" },
  { code: "PRINTER_LINES",    label: "Printer lines",    icon: LuPrinter,     iconName: "LuPrinter" },
  { code: "WRONG_SIZE",       label: "Wrong size",       icon: LuRuler,       iconName: "LuRuler" },
  { code: "WRONG_MATERIAL",   label: "Wrong Fabric",     icon: LuLayers,      iconName: "LuLayers" },
  { code: "FABRIC_FAULT",     label: "Fabric Fault",     icon: LuZap,         iconName: "LuZap" },
  { code: "PRESSING_FAULT",   label: "Pressing Fault",   icon: LuThermometer, iconName: "LuThermometer" },
  { code: "FABRIC_CREASE",    label: "Fabric Crease",    icon: LuWaves,       iconName: "LuWaves" },
  { code: "GHOSTING",         label: "Ghosting",         icon: LuGhost,       iconName: "LuGhost" },
  { code: "LINT_MARK",        label: "Lint Mark",        icon: LuSparkles,    iconName: "LuSparkles" },
  { code: "WRONG_COLOURS",    label: "Wrong Colours",    icon: LuPalette,     iconName: "LuPalette" },
  { code: "AUTOMATION_FAULT", label: "Automation Fault", icon: LuBot,         iconName: "LuBot" },
  { code: "RERUN",            label: "Re-run",           icon: LuRefreshCw,   iconName: "LuRefreshCw" },
  { code: "ARTWORK_ISSUE",    label: "Artwork Issue",    icon: LuImageOff,    iconName: "LuImageOff" },
  { code: "OTHER",            label: "Other...",         icon: LuEllipsis,    iconName: "LuEllipsis" },
];
